### ISSUE TITLE
Move tl.phar to releases

### ISSUE THREAD

**Issue by nickschuch** [larowlan/tl#1]
To save on committed binaries, what do you think about moving these into point releases in the "releases" section on github?

**Comment by larowlan** [comment]
they're in gh-pages branch now, removed them from master except for the current one

**Comment by nickschuch** [comment]
what not attach them to the tags (releases) on github?

**Comment by jibran** [comment]
+1 for the tags like https://github.com/rg3/youtube-dl

**Comment by larowlan** [comment]
How does one do that?

**Comment by larowlan** [comment]
0.0.9 is done https://github.com/larowlan/tl/releases/tag/0.0.9

Need to move the rest and change the manifest on gh-pages branch

**Comment by benjy** [comment]
Do we have to move all the old releases? Can't we just delete the gh-pages branch and move onwards using the releases on Github like you have for the latest few?

**Comment by larowlan** [comment]
The gh pages branch has the manifest.json

**Comment by benjy** [comment]
So lets just make it an empty branch with only that file?

**Comment by larowlan** [comment]
removed em

**Comment by larowlan** [comment]
agree

On 15 October 2015 at 08:27, Ben Dougherty notifications@github.com wrote:

> So lets just make it an empty branch with only that file?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/larowlan/tl/issues/1#issuecomment-148221119.

## 

Lee Rowlands
Senior Drupal Developer
PreviousNext
skype: larowlan
email: larowlan@previousnext.com.au
