### ISSUE TITLE
TL should be able to open the issue you are working on

### ISSUE THREAD

**Issue by benjy** [larowlan/tl#21]
It would be a neat feature if you could do `tl open` and it opened the issue you were currently working on, also we could support `tl open [issue]`

**Comment by larowlan** [comment]
`tl open` is already a command, so maybe `tl browser` or `tl visit` instead

On 12 October 2015 at 09:45, Ben Dougherty notifications@github.com wrote:

> It would be a neat feature if you could do tl open and it opened the
> issue you were currently working on, also we could support tl open [issue]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/larowlan/tl/issues/21.

## 

Lee Rowlands
Senior Drupal Developer
PreviousNext
skype: larowlan
email: larowlan@previousnext.com.au

**Comment by jibran** [comment]
+1 for tl visit.

Regards,
Jibran Ijaz

Jibran Ijaz
about.me/JibranIjaz
[image: Jibran Ijaz on about.me]
  http://about.me/JibranIjaz

**Comment by benjy** [comment]
tl visit works for me.

**Comment by benjy** [comment]
I thought open because that's the command that we'd use to open the link in the right tool. Maybe our current open is more like a tl show ?

**Comment by larowlan** [comment]
https://github.com/larowlan/tl/pull/23
