### ISSUE TITLE
(Feature Request) Issue number aliases

### ISSUE THREAD

**Issue by Eric115** [larowlan/tl#22]
Sometimes the issue number can be hard to remember in a hurry (such as when you start a call and then remember your timer isn't running). It would be cool to be able to 'alias' issue numbers for quicker use.
Maybe something like:

```
tl alias 3118 team-meeting
tl start team-meeting
```

**Comment by benjy** [comment]
+1, awesome idea

**Comment by larowlan** [comment]
Love it
This will give us a test case for the Schema diffing.

If we add new stuff to the schema it should auto recognise differences and
ask to re-run install command.

_However_ I think the diff SQL outputs _Drop table_ so we don't want that.

On 12 October 2015 at 15:38, Ben Dougherty notifications@github.com wrote:

> +1, awesome idea
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/larowlan/tl/issues/22#issuecomment-147295493.

## 

Lee Rowlands
Senior Drupal Developer
PreviousNext
skype: larowlan
email: larowlan@previousnext.com.au

**Comment by larowlan** [comment]
https://github.com/larowlan/tl/pull/29

No dramas with schema diff, because new table

**Comment by larowlan** [comment]
Challenge to you @Eric115 - add a list-alias command that lists out the aliases using table formatter (new issue)

**Comment by Eric115** [comment]
![image](https://cloud.githubusercontent.com/assets/5107089/10426793/2bf584b4-7116-11e5-9f23-a18e6c52d726.png)

**Comment by larowlan** [comment]
Or maybe tl alias with no arguments lists them or a --list flag out some
such

**Comment by larowlan** [comment]
@Eric115 please see #30
