### ISSUE TITLE
Add reporting features

### ISSUE THREAD

**Issue by larowlan** [larowlan/tl#55]
- [ ] % billable for day
- [ ] % billable for date range
- [ ] % hours logged since date

**Comment by benjy** [comment]
Some nice shortcuts would be handy, e.g:

billable month
billable week

Also, for hours:

hours week
hours month

**Comment by larowlan** [comment]
``` bash
# billable
tl billable month
tl billable week
# defaults to day
tl billable 
tl billable day
# logged
tl logged month
tl logged week
tl logged day
```

We should also add a `--verify` flag which reports the total logged in redmine, as well as the quantity recorded in the database

We'll need a config table for storing billable project IDs

**Comment by benjy** [comment]
> We'll need a config table for storing billable project IDs

I wonder if this should be in YAML, each user has access to different projects and tickets, and they may need a way to manipulate the non-billable/billable projects and issues?

**Comment by larowlan** [comment]
ha, that's what I ended up doing anyway - great minds etc

**Comment by nickschuch** [comment]
Could we flag tickets as billable when adding comments / tagging / creation?
