### ISSUE TITLE
Add comment param to tl start

### ISSUE THREAD

**Issue by pameeela** [larowlan/tl#69]
When running tl start it would be great to be able to add your comment at that point, rather than adding it later. Sometimes I can't remember what I did!

**Comment by benjy** [comment]
You already can do that? It's great because when you do that, it doesn't continue the entry next time you tl start, it creates a new entry. So, you can tl start non-billable "Dev meeting" and then the next time you tl start, it's a whole new entry.

**Comment by larowlan** [comment]
Yeah this ticket is about being able to change the comment sent to redmine
with -s flag, default is 'working on this'

Fwiw tl continue let's you keep going on tickets with comments

**Comment by benjy** [comment]
ahh, the comment on the issue, not the comment on the time entry :)

**Comment by benjy** [comment]
That doesn't seem to be what Pam is talking about in her comment though?

**Comment by larowlan** [comment]
Yeah I'm agreeing with you

**Comment by pameeela** [comment]
Yep Ben is right. Didn't know it could be done! I'll try it out today.
Maybe we can get the doco updated to say so :)

On Thursday, 14 January 2016, Lee Rowlands notifications@github.com wrote:

> Yeah I'm agreeing with you
> On 13 Jan 2016 10:14 pm, "Ben Dougherty" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > That doesn't seem to be what Pam is talking about in her comment though?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/larowlan/tl/issues/69#issuecomment-171274172.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/larowlan/tl/issues/69#issuecomment-171427563.

## 

Pamela Barone
+61 416 187 246

**Comment by larowlan** [comment]
Sure, the start command might already have the docs, try tl help start, if
not, easy to add

**Comment by pameeela** [comment]
Right again! Closing this one down :)

@nickschuch FYI this feature already exists!

**Comment by larowlan** [comment]
Can you keep it open, this one is about the redmine comment with the -s flag

**Comment by pameeela** [comment]
I can, but I made this one and I meant it just for the time log comment, not the issue comment. Maybe there's another one for that?

**Comment by larowlan** [comment]
Ooh, yeah there is, sorry
